### ISSUE TITLE
运行： "serve": "vue-cli-service serve"，无法正常显示

### ISSUE THREAD

**Issue by sujiewen** [staven630/vue-cli4-config#24]
/usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js run serve
yarn run v1.15.2
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 DONE  Compiled successfully in 3284ms                                                                                                                                 5:12:53 PM

  App running at:
  - Local:   http://localhost:8080 
  - Network: http://192.168.2.100:8080

  Note that the development build is not optimized.
  To create a production build, run yarn build.

URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.cdn.css[i]%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/index.js:317:13)
    at /Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/index.js:317:13)
    at /Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/sjw/Downloads/vue-cli4-config-master/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.cdn.js[i]%20%%3E'

**Comment by staven630** [comment]
源代码配置的是多站点打包，不要克隆代码直接运行，按需自行配置
